language: python
env:
  global:
  - PYTHON_VERSION=$PYTHON_VERSION
  - NUMPY_VERSION=stable
  - MAIN_CMD='python setup.py'
  - CONDA_DEPENDENCIES='scipy numpy coveralls coverage h5py mock requests six appdirs python-geotiepoints dask'
  - PIP_DEPENDENCIES=''
  - SETUP_XVFB=False
  - EVENT_TYPE='push pull_request'
  - SETUP_CMD='test'
  - CONDA_CHANNELS='conda-forge'
python:
- 2.7
- 3.4
- 3.5
- 3.6
os:
- linux
matrix:
  allow_failures:
  - os: osx
install:
- if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then travis_wait mvn; pip install "scipy>=0.14";
  fi
- pip install -r requirements.txt
- pip install dask[array]
- pip install .
- pip install coveralls
addons:
  apt_packages:
  - libhdf5-serial-dev
script: coverage run --source=pyspectral setup.py test
#virtualenv:
#  system_site_packages: true
before_install:
- sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
- sudo apt-get install -qq python-numpy
after_success: coveralls
deploy:
  provider: pypi
  user: adybbroe
  password:
    secure: SY0qo7sZXDjDx0DHvuXrHvL9VTAulgU/T33d6UWXf469jT9DOexuZ2VYLgJbYQen5FSe5JmQE0ZMdId1cb8IPP/77qCgQK6f0lRDa43fSYXhcD+fHzlQskievJrwamkRYx6WBrJbwGAKBNinUgNSaTdbh9XUugziGFiOHUfVppM=
  on:
    tags: true
    repo: pytroll/pyspectral
    python: 3.6
    distributions: sdist bdist_wheel

notifications:
  slack: pytroll:LR63XVq1cT8kVc3fnXKIZmYr
