language: python
python:
  - "2.7"
# command to install dependencies, e.g. 
install: 
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
# command to run tests, e.g. python setup.py test
#script:  python setup.py test
script: coverage run --source=pyspectral setup.py test
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
after_success: coveralls
