language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
os:
- linux
matrix:
  allow_failures:
    - os: osx
# command to install dependencies, e.g. 
install: 
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then travis_wait mvn; pip install "scipy>=0.14"; fi
  - pip install -r requirements.txt
  - pip install dask[array]  # optional
  - pip install .
  - pip install coveralls
addons:
  apt_packages:
    - libhdf5-serial-dev
# command to run tests, e.g. python setup.py test
#script:  python setup.py test
script: coverage run --source=pyspectral setup.py test
#virtualenv:
#  system_site_packages: true
before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  - sudo apt-get install -qq python-numpy
after_success: coveralls
deploy:
  provider: pypi
  user: adybbroe
  password:
    secure: A/DAh5K6A1UzARPWsiNL+qiyLfHd1dS2fhmZlE0SNcS0zN1CalyY2s7znVKTE15fSF0oV/jah/jy1PQIMBFFbAhpc6nmnDx3DxJ3d9RWxGE2hLWKn9tYUHQ07k7oiRFrwQe2bEJlaLBQfBOZ/DIe4Umc3osC65UINX03oOHsPFI=
  on:
    tags: true
    repo: pytroll/pyspectral
    python: 3.6
    distributions: sdist bdist_wheel

notifications:
  slack: pytroll:LR63XVq1cT8kVc3fnXKIZmYr
